apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-controller
  namespace: logging
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-100"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-controller-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-100"
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
    verbs: ["*"]
  - apiGroups: ["logcollector.harmonycloud.cn"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-controller-rolebinding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-100"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-controller-role
subjects:
  - kind: ServiceAccount
    name: log-controller
    namespace: logging

